[package]
name = "listbox"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
promkit = { path = "../../promkit", features = ["listbox"] }
tokio = { workspace = true }

[[bin]]
name = "listbox"
path = "src/listbox.rs"
