[package]
name = "checkbox"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
promkit = { path = "../../promkit", features = ["checkbox"] }
tokio = { workspace = true }

[[bin]]
name = "checkbox"
path = "src/checkbox.rs"
