[package]
name = "password"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
promkit = { path = "../../promkit", features = ["password"] }
tokio = { workspace = true }

[[bin]]
name = "password"
path = "src/password.rs"
