[package]
name = "tree"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
promkit = { path = "../../promkit", features = ["tree"] }
tokio = { workspace = true }

[[bin]]
name = "tree"
path = "src/tree.rs"
