[package]
name = "byop"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
promkit-widgets = { path = "../../promkit-widgets", features = ["texteditor"] }
tokio = { workspace = true }

[[bin]]
name = "byop"
path = "src/byop.rs"
