[package]
name = "promkit-widgets"
version = "0.7.0"
edition = "2024"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
description = "Widgets for promkit"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[features]
default = []
all = ["checkbox", "json", "yaml", "listbox", "prefixsearch", "serde", "spinner", "status", "table", "text", "texteditor", "tree"]
checkbox = ["listbox"]
json = ["dep:serde", "dep:serde_json", "dep:rayon"]
yaml = ["dep:serde", "dep:serde_yaml", "dep:rayon"]
listbox = []
prefixsearch = ["dep:radix_trie"]
serde = ["dep:serde", "dep:termcfg"]
spinner = ["dep:tokio"]
status = ["text"]
table = ["dep:csv", "dep:unicode-width"]
text = []
texteditor = []
tree = []

[dependencies]
anyhow = { workspace = true }
promkit-core = { path = "../promkit-core", version = "=0.5.0" }

# Optional dependencies
csv = { workspace = true, optional = true }
radix_trie = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
termcfg = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
unicode-width = { workspace = true, optional = true }

[dev-dependencies]
criterion = "0.8.2"
# Enable `json` feature when `jsonz` testing
promkit-widgets = { path = ".", features = ["json", "table", "yaml"] }
serde = { workspace = true }
toml = "0.9.8"

[[bench]]
name = "structured"
harness = false

[[bench]]
name = "table"
harness = false
