[package]
name = "promkit-widgets"
version = "0.7.0"
edition = "2024"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
description = "Widgets for promkit"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[features]
default = []
all = ["checkbox", "json", "yaml", "listbox", "serde", "spinner", "status", "text", "texteditor", "tree"]
checkbox = ["listbox"]
json = ["dep:serde_json", "dep:rayon"]
yaml = ["dep:serde_yaml", "dep:rayon"]
listbox = []
serde = ["dep:serde", "dep:termcfg"]
spinner = ["dep:tokio"]
status = ["text"]
text = []
texteditor = []
tree = []

[dependencies]
anyhow = { workspace = true }
promkit-core = { path = "../promkit-core", version = "=0.5.0" }

# Optional dependencies
rayon = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true, optional = true }
termcfg = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
# Enable `json` feature when `jsonz` testing
promkit-widgets = { path = ".", features = ["json", "yaml"] }
toml = "0.9.8"
