[package]
name = "promkit"
version = "0.14.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2021"
description = "A toolkit for building your own interactive command-line tools"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[lib]
name = "promkit"
path = "src/lib.rs"

[features]
# Bundles
default = []
all = [
    "runtime",
    "validate",
    "suggest",
    "checkbox",
    "json",
    "yaml",
    "listbox",
    "serde",
    "spinner",
    "status",
    "table",
    "text",
    "texteditor",
    "tree",
]

# Foundation
core = ["dep:promkit-core"]
runtime = [
    "core",
    "dep:anyhow",
    "dep:async-trait",
    "dep:futures",
    "dep:scopeguard",
    "dep:tokio",
]
widgets = ["core", "dep:promkit-widgets"]

# Capabilities
validate = []
suggest = ["dep:radix_trie"]

# Widgets
checkbox = ["widgets", "promkit-widgets/checkbox"]
json = ["widgets", "promkit-widgets/json"]
yaml = ["widgets", "promkit-widgets/yaml"]
listbox = ["widgets", "promkit-widgets/listbox"]
serde = ["widgets", "promkit-widgets/serde"]
spinner = ["widgets", "promkit-widgets/spinner"]
status = ["widgets", "promkit-widgets/status"]
table = ["widgets", "promkit-widgets/table"]
text = ["widgets", "promkit-widgets/text"]
texteditor = ["widgets", "promkit-widgets/texteditor"]
tree = ["widgets", "promkit-widgets/tree"]

[dependencies]
anyhow = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
promkit-core = { path = "../promkit-core", version = "=0.5.0", optional = true }
promkit-widgets = { path = "../promkit-widgets", version = "=0.7.0", default-features = false, optional = true }
radix_trie = { workspace = true, optional = true }
scopeguard = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
